### ISSUE TITLE
Hot Edge not available on secondary displays

### ISSUE THREAD

**Issue by xpseudonym** [jdoda/hotedge#30] opened 2024-01-13 13:52 UTC
Re [this feature request](https://github.com/jdoda/hotedge/issues/8#issuecomment-857330443) it seems that the hot edge _should_ be on all my screens - my use case is as per point 2/ of that feature request comment, I have my primary screen set to a secondary display and when it's plugged in the hot edge remains on the laptop internal display while the dash has moved to the primary screen/ secondary display - this was going to be a feature request, but as I see the feature should be implemented it's a bug report of the feature not working...

**Comment by jtherrmann** [comment] 2024-01-18 20:30
I have the same issue on Debian 12 with GNOME Shell 43.9 on Wayland. With the a laptop connected to two external monitors, with Primary Display set to one of the external monitors. Hot edge only works on the laptop display.

**Comment by jdoda** [comment] 2024-01-18 21:37
Thanks for the report. That's definitely a bug. The hot edge should be present on all monitors, *unless* there's another monitor directly below (in that case the hot edge would prevent you from moving the cursor down to the lower monitor, so we don't add one). 

I haven't been able to reproduce the bug locally, so I'll need some logs to try to track down the problem. If you're on GNOME Shell 45, you'll need to:

1. install this extension https://extensions.gnome.org/extension/6706/enable-debug-logs/ to enable debug logging.
2. disable, and then re-enable Hot Edge.
3. run `journalctl -g hotedge -r` in a terminal, and copy-paste the output into a comment on this issue.

For GNOME Shell 43, the process would be the same, except instead of installing an extension to enable debug logging, you instead need to open the Hot Edge preferences and set the "Log Level" to 0.

**Comment by xpseudonym** [comment] 2024-01-18 22:24
> ... _unless_ there's another monitor directly below (in that case the hot edge would prevent you from moving the cursor down to the lower monitor, so we don't add one).

AH!
That *might* be it - I don't have a monitor directly below - but, I have two screens on pedestals both above my laptop (internal) monitor - which is open in the middle of the two and below...  And, I can see that it would be a problem getting to the internal monitor, but I just tend not to use it in this configuration...
So, does this sound like problem solved?

**Comment by xpseudonym** [comment] 2024-01-18 23:53
This is what gnome's Displays settings look like:
![image](https://github.com/jdoda/hotedge/assets/5032475/a9e2f41e-3828-4eb9-a1ba-d3aec5690093)

**Comment by jtherrmann** [comment] 2024-01-19 02:20
> _unless_ there's another monitor directly below (in that case the hot edge would prevent you from moving the cursor down to the lower monitor, so we don't add one).

Yep, this solved it for me as well. I had it configured so that just the very top corner of my laptop display sits beneath the very bottom corner of my external display. Re-adjusting so that the two displays connect at the vertical edges rather than the horizontal edges fixed the issue. Thanks for the quick response!

**Comment by jdoda** [comment] 2024-01-19 02:21
@xpseudonym Yeah, in that configuration I would expect a hot edge only on monitor 1, but not 2 or 3 (because 1 is below them). If you disable monitor 1, then you should have a hot edge on 2 and 3.

So, this is all working as designed, but one improvement that could be made (at least in theory) would be to, instead of not having any hot edge at all when there's a monitor below, have a partial hot edge that only covers the bottom of the monitor where it doesn't actually overlap with the monitor below. I'm not sure if this is a good idea or not. The implementation would be a bit complex, and I'm worried that the behaviour would be a bit unexpected and possibly confusing (though clearly the current behaviour is also a little confusing). Any thoughts about this idea?

**Comment by jtherrmann** [comment] 2024-01-19 02:24
@jdoda Re-adjusting the displays is a good enough fix for me personally. I would suggest adding a note somewhere, perhaps at https://extensions.gnome.org/extension/4222/hot-edge/, in the README, and/or the extension settings, explaining this behavior. (It may already be in the README and I just didn't bother to look for it.)

**Comment by xpseudonym** [comment] 2024-01-19 12:20
Hmm, this sounded like a fix - but, now I'm back at my machine re-arranging screens, I'm not so sure it is...  When I set up my screens like so:
![image](https://github.com/jdoda/hotedge/assets/5032475/1088684c-e3cd-4d9d-8717-f3ba5dd23815)
I'm unable to move my cursor between 3 and 2 - and have to go via the internal monitor screen - and, there's no hotedge at the bottom of 3 and 2 - but, then I thought some more...
And, if I turn off my internal monitor screen, like so:
![image](https://github.com/jdoda/hotedge/assets/5032475/474b8662-18af-495d-8ba2-f3610bfc48f2)
Then everything works swimmingly :-)  Except, I don't have my internal monitor screen - which, I don't think matters, but might...
Some thoughts.
(Having partially active hotedges does sound confusing and a lot of work.)
@jtherrmann I wonder if you could post your display arrangement as reported by Gnome Settings Displays?

**Comment by eode** [comment] 2024-01-19 16:17
I don't know what the implementation is, exactly -- depends on how the pressure setting works.  But if the pressure setting counts the number of times the mouse tries to leave the screen edge and fails, then you should just be able to do the hot edge on all monitors, as long as the number of times > 1, because the mouse would simply pass through and not trigger the event.

That's highly implementation-specific, and I don't know what the implementation actually is, so this may not work at all.  But if it does, this might be a comparatively simple way of making the hot edge work for all bottom edges on configurations like the one in [this comment](https://github.com/jdoda/hotedge/issues/30#issuecomment-1899401468).

In the stacked areas:
* Mouse approaches bottom of screen
* mouse passes through, so doesn't register a screen edge bump (or at least, not more than one)

In the non-stacked areas:
* Mouse approaches bottom of screen
* Mouse registers multiple edge bumps, because humans never just stop *EXACTLY* on the edge
* Plugin is triggered.

Now, if the edge pressure is measured by *speed*, then it might trigger when passing through if it were passing through fast enough, and I can't think of a simple solution in that case.

**Comment by eode** [comment] 2024-01-19 16:33
Huh.  Looks like the second method would work pretty well.  The hot edge has the display, and you can get the pointer's display with:

```javascript
Gdk = imports.gi.Gdk
let display = Gdk.Display.get_default();
let deviceManager = display.get_device_manager();
let pointer = deviceManager.get_client_pointer();
let [screen, pointerX, pointerY] = pointer.get_position();
```

That's about all I've got time for, but hopefully that's useful.

**Comment by jtherrmann** [comment] 2024-01-20 03:18
> @jtherrmann I wonder if you could post your display arrangement as reported by Gnome Settings Displays?

![display-settings](https://github.com/jdoda/hotedge/assets/19476938/361f2c2c-4844-4b27-a2e6-6279c914e98f)

It's difficult to tell from the screenshot, but the displays are connected at their vertical edges, which allows Hot Edge to work on Display 2. When they are connected at their horizontal edges, Hot Edge no longer works on Display 2.

**Comment by xpseudonym** [comment] 2024-01-20 12:10
Ah, thanks @jtherrmann , that is rather different to how I arranged things in [this comment](https://github.com/jdoda/hotedge/issues/30#issuecomment-1900318637)...

**Comment by jdoda** [comment] 2024-01-21 03:39
@eode thanks for looking at this. PressureBarrier measures pressure in terms # of pixels the cursor would have moved past the barrier, based on the mouse input. The fundamental problem, though, is that the cursor doesn't actually pass through the barrier, so if you had a barrier above another screen, the cursor would not be able to move to that screen. Even if that did work, I think the risk of accidental activation and unpredictable behaviour would be too high.

**Comment by jdoda** [comment] 2024-01-21 03:41
Since this is expected behaviour, I'm going to close this issue. I am going to update the readme and the text on the extensions site to provide more detail about the behaviour of the extension to hopefully make this situation less confusing, and I'll take a closer look at implementing partial hot edges to see if that would be as bad as I fear.

**Closed by jdoda** 2024-01-21 03:41 UTC

**Comment by eode** [comment] 2024-01-21 22:42
Makes sense.  Thanks for your work on this.
